apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ru8lrsc3m-python-gitops
  description: This is GitOps manifest for ru8lrsc3m-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=ru8lrsc3m-python
    backstage.io/kubernetes-id: ru8lrsc3m-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: ru8lrsc3m-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:ru8lrsc3m-python
